using Lambda.GeradorPDF.Helpers;
using Microsoft.AspNetCore.Mvc;
using WkHtmlToPdfDotNet;

namespace Lambda.GeradorPDF.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class GenerateController : ControllerBase
    {
        private readonly ILogger<GenerateController> _logger;
        private readonly IPdfGeneratorHelper _generator;

        public GenerateController(ILogger<GenerateController> logger, IPdfGeneratorHelper generator)
        {
            _logger = logger;
            _generator = generator;
        }

        /// <summary>
        ///  Return PDF Download
        /// </summary>
        /// <returns></returns>
        // GET generate/pdf
        [HttpGet("pdf")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(FileContentResult))]
        public IActionResult Pdf()
        {
            var pdf = _generator.Generate("<h1>Hello World - Generated Bytes</h1>", Orientation.Portrait);
            return File(pdf, "application/pdf", "Test.pdf");
        }

        /// <summary>
        ///  Return PDF Download
        /// </summary>
        /// <returns></returns>
        [HttpPost("pdf")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(FileContentResult))]
        public IActionResult GeneratePDF([FromBody] string html)
        {
            var pdf = _generator.Generate(html, Orientation.Portrait);
            return File(pdf, "application/pdf", "Test.pdf");
        }
    }
}
